#!/bin/bash
clear
echo -e "\E[44;1;37m     INSTALACAO BOT SSH TESTE     \E[0m"
echo -e "\nINSTALANDO AGUARDE...."
apt update -y > /dev/null 2>&1 && apt install unzip at jq curl -y > /dev/null 2>&1
mkdir $HOME/BOT
cd $HOME/BOT && wget dropbox.com/s/3vr186z7rfcqn59/botteste.zip?dl=1
unzip botteste.zip?dl=1 > /dev/null 2>&1 && rm botteste.zip?dl=1 > /dev/null 2>&1
chmod +x $(ls)
mv botteste /bin/botteste
clear && echo -e "INSTALADO COM SUCESSO !\nPARA ATIVAR EXECULTE O COMANDO botteste"
cd $HOME && rm inst-botteste > /dev/null 2>&1
